### ISSUE TITLE
Symbol not found in 3.2.3

### ISSUE THREAD

**Issue by imperiacorp** [DataDome/datadome-alamofire-package#11]
Hello, I have an issue, app crashes on start with such log
dependency manager: CocoaPods

dyld[43259]: Symbol not found: _$s9Alamofire11RetryResultO05doNotB0yA2CmFWC
  Referenced from: <4CDD4E66-2ABC-388F-99F5-9336BB28854E> /Users/user/Library/Developer/CoreSimulator/Devices/82AA21FE-546C-4B27-86C0-1E965BA6F4FE/data/Containers/Bundle/Application/F35D7787-0646-4362-8632-4DB3EB755FE0/Mouser.app/Frameworks/DataDomeAlamofire.framework/DataDomeAlamofire
  Expected in:     <96E9ADF6-0940-331A-83F2-57FDD1AD0DBC> /Users/user/Library/Developer/CoreSimulator/Devices/82AA21FE-546C-4B27-86C0-1E965BA6F4FE/data/Containers/Bundle/Application/F35D7787-0646-4362-8632-4DB3EB755FE0/Mouser.app/Frameworks/Alamofire.framework/Alamofire

I checked alamofire has RetryResult enum in it.

**Comment by Kireyin** [comment]
Hello,

Can you provide steps to reproduce please? 
Also, what version of Alamofire are you using?
