### ISSUE TITLE
Compilation error with version 3.2.1

### ISSUE THREAD

**Issue by gsl-sebastienpecoul** [DataDome/datadome-alamofire-package#7]
Hello, 
I got a few compilation errors when trying to build with last version.
Capture of Xcode errors:

![Capture d’écran 2023-07-21 à 16 06 05](https://github.com/DataDome/datadome-alamofire-package/assets/82036055/c25afad3-4424-4021-8cfe-66563d66eb35)

**Comment by Kireyin** [comment]
Hello @gsl-sebastienpecoul 

Thank you for raising the issue, we will take a look and provide a fix. 
In the mean time, we have remove the 3.2.1 tag, we will add it back when the issue is fixed.
